# Generated by Django 6.0.5 on 2026-06-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('runs', models.IntegerField()),
                ('balls', models.IntegerField()),
                ('four', models.IntegerField()),
                ('six', models.IntegerField()),
                ('sr', models.FloatField()),
                ('team', models.CharField(max_length=100)),
                ('opp', models.CharField(max_length=100)),
            ],
        ),
    ]
