# Generated by Django 6.0.5 on 2026-07-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crickstats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cricket',
            old_name='wickets',
            new_name='wicket',
        ),
    ]
