var fs = require('fs')
// fs.writeFileSync('hello.txt','Good Morning')
// fs.appendFileSync('hello.txt',' It is a good day')
fs.appendFileSync('h1.txt',' It is a good day')
// var data = fs.readFileSync('hello.txt')
// console.log(data)
// console.log(data.toString())
// var data1 = fs.readFileSync('hello.txt','UTF-8')
// console.log(data1)
// fs.renameSync('hello.txt','B4.txt')
fs.unlinkSync('h1.txt')