# Generated by Django 6.0.5 on 2026-07-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('author', models.CharField()),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('ISBN', models.CharField()),
            ],
        ),
    ]
